import os, sys

# This script generates the MainActivity.kt file with native overlay window support
# It writes the file in parts to avoid shell escaping issues

out_path = r'C:\Users\Administrator\.qclaw\workspace\quick-reply-app\quick_reply_app\android\app\src\main\kotlin\com\quickreply\quick_reply_app\MainActivity.kt'

lines = []
lines.append('package com.quickreply.quick_reply_app')
lines.append('')
lines.append('import android.annotation.SuppressLint')
lines.append('import android.content.Intent')
lines.append('import android.graphics.PixelFormat')
lines.append('import android.net.Uri')
lines.append('import android.os.Build')
lines.append('import android.os.Handler')
lines.append('import android.os.Looper')
lines.append('import android.provider.Settings')
lines.append('import android.view.Gravity')
lines.append('import android.view.MotionEvent')
lines.append('import android.view.View')
lines.append('import android.view.WindowManager')
lines.append('import android.widget.FrameLayout')
lines.append('import android.widget.ImageView')
lines.append('import android.widget.LinearLayout')
lines.append('import android.widget.ScrollView')
lines.append('import android.widget.TextView')
lines.append('import io.flutter.embedding.android.FlutterActivity')
lines.append('import io.flutter.embedding.engine.FlutterEngine')
lines.append('import io.flutter.plugin.common.MethodChannel')
lines.append('import android.graphics.Color')
lines.append('import android.graphics.drawable.GradientDrawable')
lines.append('import android.util.TypedValue')
lines.append('')
lines.append('class MainActivity : FlutterActivity() {')
lines.append('    private val CHANNEL = "app.quickreply/overlay"')
lines.append('    private var overlayView: View? = null')
lines.append('    private var isPanelExpanded = false')
lines.append('    private var wm: WindowManager? = null')
lines.append('    private var msgTitle = ""')
lines.append('    private var msgContent = ""')
lines.append('    private var msgImages = listOf<String>()')
lines.append('    private var msgFiles = listOf<String>()')
lines.append('    private val handler = Handler(Looper.getMainLooper())')
lines.append('    private var posX = 0')
lines.append('    private var posY = 200')
lines.append('')
lines.append('    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {')
lines.append('        super.configureFlutterEngine(flutterEngine)')
lines.append('        wm = getSystemService(WINDOW_SERVICE) as WindowManager')
lines.append('        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL)')
lines.append('            .setMethodCallHandler { call, result ->')
lines.append('                when (call.method) {')
lines.append('                    "checkPermission" -> result.success(Settings.canDrawOverlays(this))')
lines.append('                    "requestPermission" -> {')
lines.append('                        startActivity(Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,')
lines.append('                            Uri.parse("package:$packageName")))')
lines.append('                        result.success(true)')
lines.append('                    }')
lines.append('                    "showOverlay" -> {')
lines.append('                        msgTitle = call.argument<String>("title") ?: ""')
lines.append('                        msgContent = call.argument<String>("content") ?: ""')
lines.append('                        msgImages = call.argument<List<String>>("images") ?: listOf()')
lines.append('                        msgFiles = call.argument<List<String>>("files") ?: listOf()')
lines.append('                        showOverlay()')
lines.append('                        result.success(true)')
lines.append('                    }')
lines.append('                    "closeOverlay" -> { closeOverlay(); result.success(true) }')
lines.append('                    "updateOverlay" -> {')
lines.append('                        msgTitle = call.argument<String>("title") ?: ""')
lines.append('                        msgContent = call.argument<String>("content") ?: ""')
lines.append('                        msgImages = call.argument<List<String>>("images") ?: listOf()')
lines.append('                        msgFiles = call.argument<List<String>>("files") ?: listOf()')
lines.append('                        refreshPanel()')
lines.append('                        result.success(true)')
lines.append('                    }')
lines.append('                    else -> result.notImplemented()')
lines.append('                }')
lines.append('            }')
lines.append('    }')
lines.append('')
lines.append('    private fun dp(v: Int) = (v * resources.displayMetrics.density).toInt()')
lines.append('')
lines.append('    private fun showOverlay() {')
lines.append('        if (overlayView != null) { refreshPanel(); return }')
lines.append('        if (!Settings.canDrawOverlays(this)) return')
lines.append('        handler.post {')
lines.append('            try {')
lines.append('                val v = makeBubble()')
lines.append('                val p = bubbleParams()')
lines.append('                wm?.addView(v, p)')
lines.append('                overlayView = v')
lines.append('                isPanelExpanded = false')
lines.append('            } catch (e: Exception) { e.printStackTrace() }')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    private fun closeOverlay() {')
lines.append('        handler.post {')
lines.append('            try { overlayView?.let { wm?.removeView(it) } } catch (_: Exception) {}')
lines.append('            overlayView = null; isPanelExpanded = false')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    private fun refreshPanel() {')
lines.append('        handler.post {')
lines.append('            if (isPanelExpanded && overlayView != null) {')
lines.append('                try {')
lines.append('                    overlayView?.findViewWithTag<TextView>("content_text")?.text =')
lines.append('                        if (msgContent.length > 80) msgContent.substring(0, 80) + "\\u2026" else msgContent')
lines.append('                    overlayView?.findViewWithTag<TextView>("title_text")?.text = msgTitle')
lines.append('                } catch (_: Exception) {}')
lines.append('            }')
lines.append('        }')
lines.append('    }')
lines.append('')

# Bubble
lines.append('    @SuppressLint("ClickableViewAccessibility")')
lines.append('    private fun makeBubble(): FrameLayout {')
lines.append('        val container = FrameLayout(this)')
lines.append('        val bubble = ImageView(this).apply {')
lines.append('            background = GradientDrawable().apply {')
lines.append('                shape = GradientDrawable.OVAL')
lines.append('                colors = intArrayOf(0xFF2563EB.toInt(), 0xFF7C3AED.toInt())')
lines.append('                gradientType = GradientDrawable.LINEAR_GRADIENT')
lines.append('            }')
lines.append('            setImageResource(android.R.drawable.ic_menu_send)')
lines.append('            setColorFilter(Color.WHITE)')
lines.append('            setPadding(dp(10), dp(10), dp(10), dp(10))')
lines.append('            scaleType = ImageView.ScaleType.FIT_CENTER')
lines.append('        }')
lines.append('        val size = dp(48)')
lines.append('        container.addView(bubble, FrameLayout.LayoutParams(size, size, Gravity.CENTER))')
lines.append('        bubble.setOnClickListener { if (!isPanelExpanded) showPanel() }')
lines.append('')
lines.append('        var itx = 0f; var ity = 0f; var drag = false')
lines.append('        bubble.setOnTouchListener { v, ev ->')
lines.append('            when (ev.action) {')
lines.append('                MotionEvent.ACTION_DOWN -> { itx = ev.rawX; ity = ev.rawY; drag = false }')
lines.append('                MotionEvent.ACTION_MOVE -> {')
lines.append('                    val dx = (ev.rawX - itx).toInt(); val dy = (ev.rawY - ity).toInt()')
lines.append('                    if (Math.abs(dx) > 10 || Math.abs(dy) > 10) {')
lines.append('                        drag = true')
lines.append('                        try {')
lines.append('                            val p = overlayView?.layoutParams as? WindowManager.LayoutParams')
lines.append('                            if (p != null) { posX += dx; posY += dy; p.x = posX; p.y = posY; wm?.updateViewLayout(overlayView, p) }')
lines.append('                        } catch (_: Exception) {}')
lines.append('                        itx = ev.rawX; ity = ev.rawY')
lines.append('                    }')
lines.append('                }')
lines.append('                MotionEvent.ACTION_UP -> { if (!drag) v.performClick() }')
lines.append('            }')
lines.append('            true')
lines.append('        }')
lines.append('        return container')
lines.append('    }')
lines.append('')
lines.append('    private fun bubbleParams(): WindowManager.LayoutParams {')
lines.append('        val type = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY')
lines.append('            else @Suppress("DEPRECATION") WindowManager.LayoutParams.TYPE_PHONE')
lines.append('        return WindowManager.LayoutParams(')
lines.append('            WindowManager.LayoutParams.WRAP_CONTENT, WindowManager.LayoutParams.WRAP_CONTENT,')
lines.append('            type, WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE, PixelFormat.TRANSLUCENT')
lines.append('        ).apply { gravity = Gravity.TOP or Gravity.START; x = posX; y = posY }')
lines.append('    }')
lines.append('')

# Panel
lines.append('    @SuppressLint("ClickableViewAccessibility")')
lines.append('    private fun showPanel() {')
lines.append('        val old = overlayView ?: return')
lines.append('        try { wm?.removeView(old) } catch (_: Exception) {}')
lines.append('        handler.post {')
lines.append('            try {')
lines.append('                val panel = makePanel()')
lines.append('                val p = panelParams()')
lines.append('                wm?.addView(panel, p)')
lines.append('                overlayView = panel')
lines.append('                isPanelExpanded = true')
lines.append('            } catch (e: Exception) { e.printStackTrace() }')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    @SuppressLint("ClickableViewAccessibility")')
lines.append('    private fun makePanel(): LinearLayout {')
lines.append('        val root = LinearLayout(this).apply {')
lines.append('            orientation = LinearLayout.VERTICAL')
lines.append('            background = GradientDrawable().apply { setColor(Color.WHITE); cornerRadius = dp(16).toFloat() }')
lines.append('            elevation = dp(12).toFloat()')
lines.append('        }')
lines.append('')
lines.append('        // Header')
lines.append('        val header = LinearLayout(this).apply {')
lines.append('            orientation = LinearLayout.HORIZONTAL; gravity = Gravity.CENTER_VERTICAL')
lines.append('            background = GradientDrawable().apply {')
lines.append('                colors = intArrayOf(0xFF2563EB.toInt(), 0xFF7C3AED.toInt())')
lines.append('                gradientType = GradientDrawable.LINEAR_GRADIENT')
lines.append('                cornerRadii = floatArrayOf(dp(15).toFloat(),dp(15).toFloat(),dp(15).toFloat(),dp(15).toFloat(),0f,0f,0f,0f)')
lines.append('            }')
lines.append('            setPadding(dp(14), dp(10), dp(8), dp(10))')
lines.append('        }')
lines.append('        header.addView(ImageView(this).apply {')
lines.append('            setImageResource(android.R.drawable.ic_menu_send); setColorFilter(Color.WHITE)')
lines.append('            layoutParams = LinearLayout.LayoutParams(dp(16), dp(16))')
lines.append('        })')
lines.append('        header.addView(TextView(this).apply {')
lines.append('            text = " \\u5FEB\\u56DE\\u590D"; setTextColor(Color.WHITE)')
lines.append('            setTextSize(TypedValue.COMPLEX_UNIT_SP, 14f)')
lines.append('            layoutParams = LinearLayout.LayoutParams(0, LinearLayout.LayoutParams.WRAP_CONTENT, 1f)')
lines.append('        })')
lines.append('        header.addView(TextView(this).apply {')
lines.append('            text = " \\u2014 "; setTextColor(0xB0BEC5FF.toInt())')
lines.append('            setTextSize(TypedValue.COMPLEX_UNIT_SP, 16f)')
lines.append('            setOnClickListener { collapseToBubble() }')
lines.append('        })')
lines.append('        header.addView(TextView(this).apply {')
lines.append('            text = " \\u2715 "; setTextColor(0xB0BEC5FF.toInt())')
lines.append('            setTextSize(TypedValue.COMPLEX_UNIT_SP, 14f)')
lines.append('            setOnClickListener { closeOverlay() }')
lines.append('        })')
lines.append('        root.addView(header)')
lines.append('')
lines.append('        // Content')
lines.append('        val scroll = ScrollView(this)')
lines.append('        val contentWrap = LinearLayout(this).apply {')
lines.append('            orientation = LinearLayout.VERTICAL; setPadding(dp(12), dp(12), dp(12), dp(8))')
lines.append('        }')
lines.append('        contentWrap.addView(TextView(this).apply {')
lines.append('            tag = "title_text"; text = msgTitle')
lines.append('            setTextColor(0xFF1E293B.toInt())')
lines.append('            setTextSize(TypedValue.COMPLEX_UNIT_SP, 14f); setTypeface(null, android.graphics.Typeface.BOLD)')
lines.append('        })')
lines.append('        contentWrap.addView(TextView(this).apply {')
lines.append('            tag = "content_text"')
lines.append('            text = if (msgContent.length > 80) msgContent.substring(0, 80) + "\\u2026" else msgContent')
lines.append('            setTextColor(0xFF64748B.toInt())')
lines.append('            setTextSize(TypedValue.COMPLEX_UNIT_SP, 13f)')
lines.append('            setPadding(0, dp(6), 0, 0)')
lines.append('        })')
lines.append('')

# Attachment indicators
lines.append('        if (msgImages.isNotEmpty() || msgFiles.isNotEmpty()) {')
lines.append('            val attachRow = LinearLayout(this).apply {')
lines.append('                orientation = LinearLayout.HORIZONTAL; setPadding(0, dp(8), 0, 0)')
lines.append('            }')
lines.append('            for (i in msgImages.indices) {')
lines.append('                attachRow.addView(makeChip("\\uD83D\\uDCF7 \\u56FE${i+1}"))')
lines.append('            }')
lines.append('            for (f in msgFiles) {')
lines.append('                val name = f.substringAfterLast("/")