import os

out = r'C:\Users\Administrator\.qclaw\workspace\quick-reply-app\quick_reply_app\android\app\src\main\kotlin\com\quickreply\quick_reply_app\MainActivity.kt'

# Read the generated content from gen_overlay.py and extend it
# Instead, let's just write directly using Python file I/O

with open(out, 'w', encoding='utf-8') as f:
    # Part 1: imports and class declaration
    f.write("package com.quickreply.quick_reply_app\n\n")
    f.write("import android.annotation.SuppressLint\n")
    f.write("import android.content.Intent\n")
    f.write("import android.graphics.PixelFormat\n")
    f.write("import android.net.Uri\n")
    f.write("import android.os.Build\n")
    f.write("import android.os.Handler\n")
    f.write("import android.os.Looper\n")
    f.write("import android.provider.Settings\n")
    f.write("import android.view.Gravity\n")
    f.write("import android.view.MotionEvent\n")
    f.write("import android.view.View\n")
    f.write("import android.view.WindowManager\n")
    f.write("import android.widget.FrameLayout\n")
    f.write("import android.widget.ImageView\n")
    f.write("import android.widget.LinearLayout\n")
    f.write("import android.widget.ScrollView\n")
    f.write("import android.widget.TextView\n")
    f.write("import io.flutter.embedding.android.FlutterActivity\n")
    f.write("import io.flutter.embedding.engine.FlutterEngine\n")
    f.write("import io.flutter.plugin.common.MethodChannel\n")
    f.write("import android.graphics.Color\n")
    f.write("import android.graphics.drawable.GradientDrawable\n")
    f.write("import android.util.TypedValue\n\n")

    f.write("class MainActivity : FlutterActivity() {\n")
    f.write('    private val CHANNEL = "app.quickreply/overlay"\n')
    f.write("    private var overlayView: View? = null\n")
    f.write("    private var isPanelExpanded = false\n")
    f.write("    private var wm: WindowManager? = null\n")
    f.write('    private var msgTitle = ""\n')
    f.write('    private var msgContent = ""\n')
    f.write("    private var msgImages = listOf<String>()\n")
    f.write("    private var msgFiles = listOf<String>()\n")
    f.write("    private val handler = Handler(Looper.getMainLooper())\n")
    f.write("    private var posX = 0\n")
    f.write("    private var posY = 200\n\n")

    # configureFlutterEngine
    f.write("    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {\n")
    f.write("        super.configureFlutterEngine(flutterEngine)\n")
    f.write("        wm = getSystemService(WINDOW_SERVICE) as WindowManager\n")
    f.write("        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL)\n")
    f.write("            .setMethodCallHandler { call, result ->\n")
    f.write("                when (call.method) {\n")
    f.write('                    "checkPermission" -> result.success(Settings.canDrawOverlays(this))\n')
    f.write('                    "requestPermission" -> {\n')
    f.write("                        startActivity(Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,\n")
    f.write('                            Uri.parse("package:$packageName")))\n')
    f.write("                        result.success(true)\n")
    f.write("                    }\n")
    f.write('                    "showOverlay" -> {\n')
    f.write('                        msgTitle = call.argument<String>("title") ?: ""\n')
    f.write('                        msgContent = call.argument<String>("content") ?: ""\n')
    f.write('                        msgImages = call.argument<List<String>>("images") ?: listOf()\n')
    f.write('                        msgFiles = call.argument<List<String>>("files") ?: listOf()\n')
    f.write("                        showOverlay()\n")
    f.write("                        result.success(true)\n")
    f.write("                    }\n")
    f.write('                    "closeOverlay" -> { closeOverlay(); result.success(true) }\n')
    f.write('                    "updateOverlay" -> {\n')
    f.write('                        msgTitle = call.argument<String>("title") ?: ""\n')
    f.write('                        msgContent = call.argument<String>("content") ?: ""\n')
    f.write('                        msgImages = call.argument<List<String>>("images") ?: listOf()\n')
    f.write('                        msgFiles = call.argument<List<String>>("files") ?: listOf()\n')
    f.write("                        refreshPanel()\n")
    f.write("                        result.success(true)\n")
    f.write("                    }\n")
    f.write("                    else -> result.notImplemented()\n")
    f.write("                }\n")
    f.write("            }\n")
    f.write("    }\n\n")

    f.write("    private fun dp(v: Int) = (v * resources.displayMetrics.density).toInt()\n\n")

    # showOverlay
    f.write("    private fun showOverlay() {\n")
    f.write("        if (overlayView != null) { refreshPanel(); return }\n")
    f.write("        if (!Settings.canDrawOverlays(this)) return\n")
    f.write("        handler.post {\n")
    f.write("            try {\n")
    f.write("                val v = makeBubble()\n")
    f.write("                val p = bubbleParams()\n")
    f.write("                wm?.addView(v, p)\n")
    f.write("                overlayView = v\n")
    f.write("                isPanelExpanded = false\n")
    f.write("            } catch (e: Exception) { e.printStackTrace() }\n")
    f.write("        }\n")
    f.write("    }\n\n")

    # closeOverlay
    f.write("    private fun closeOverlay() {\n")
    f.write("        handler.post {\n")
    f.write("            try { overlayView?.let { wm?.removeView(it) } } catch (_: Exception) {}\n")
    f.write("            overlayView = null; isPanelExpanded = false\n")
    f.write("        }\n")
    f.write("    }\n\n")

    # refreshPanel
    f.write("    private fun refreshPanel() {\n")
    f.write("        handler.post {\n")
    f.write("            if (isPanelExpanded && overlayView != null) {\n")
    f.write("                try {\n")
    f.write('                    overlayView?.findViewWithTag<TextView>("content_text")?.text =\n')
    f.write('                        if (msgContent.length > 80) msgContent.substring(0, 80) + "\\u2026" else msgContent\n')
    f.write('                    overlayView?.findViewWithTag<TextView>("title_text")?.text = msgTitle\n')
    f.write("                } catch (_: Exception) {}\n")
    f.write("            }\n")
    f.write("        }\n")
    f.write("    }\n\n")

print("Part 1 written successfully")
