org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+UseG1GC
org.gradle.workers.max=2
android.useAndroidX=true
android.enableJetifier=false
org.gradle.caching=true
kotlin.incremental=true
org.gradle.daemon=true
org.gradle.parallel=true
